version: '3'
services:

  mysql:
    image: mysql:5.7.13
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
      - MYSQL_DATABASE=service_template

  prometheus:
    image: prom/prometheus:v2.23.0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  zipkin:
    image: openzipkin/zipkin:2.21
    ports:
      - "9411:9411"
    environment:
      JAVA_OPTS: -Xmx64m

